version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    # comment out if you want to externally connect DB
    # ports:
    #   - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${POSTGRES_USER:-skyvern}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-skyvern}
      - POSTGRES_DB=${POSTGRES_DB:-skyvern}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-skyvern}"]
      interval: 5s
      timeout: 5s
      retries: 5

  skyvern:
    image: public.ecr.aws/skyvern/skyvern:latest
    restart: on-failure
    # comment out if you want to externally call skyvern API
    ports:
      - 8020:8000
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./log:/data/log
      - ./.streamlit:/app/.streamlit
    environment:
      - DATABASE_STRING=postgresql+psycopg://${POSTGRES_USER:-skyvern}:${POSTGRES_PASSWORD:-skyvern}@postgres:5432/${POSTGRES_DB:-skyvern}
      - BROWSER_TYPE=chromium-headful
      - ENABLE_OPENAI=${ENABLE_OPENAI:-true}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # If you want to use other LLM provider, like azure and anthropic:
      - ENABLE_ANTHROPIC=${ENABLE_ANTHROPIC:-false}
      # - LLM_KEY=${LLM_KEY:-ANTHROPIC_CLAUDE3.5_SONNET}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENABLE_AZURE=${ENABLE_AZURE:-false}
      - AZURE_DEPLOYMENT=${AZURE_DEPLOYMENT}
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_API_BASE=${AZURE_API_BASE}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/app/.streamlit/secrets.toml"]
      interval: 5s
      timeout: 5s
      retries: 5

  skyvern-ui:
    image: public.ecr.aws/skyvern/skyvern-ui:latest
    restart: on-failure
    ports:
      - 8083:8080
      - 9090:9090
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./.streamlit:/app/.streamlit
    environment:
      # if you want to run skyvern on a remote server,
      # you need to change the host in VITE_WSS_BASE_URL and VITE_API_BASE_URL to match your server ip
      - VITE_WSS_BASE_URL=${VITE_WSS_BASE_URL:-ws://localhost:8000/api/v1}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000/api/v1}
      - VITE_SKYVERN_API_KEY=${VITE_SKYVERN_API_KEY}
    depends_on:
      skyvern:
        condition: service_healthy
